//  op,			code,		func
xx(CNST,		0,			CNSTCal)
xx(ARG,			1,			ARGCal)
xx(ASGN,		2,			ASGNCal)
xx(INDIR,		3,			INDIRCal)
xx(CALL,		4,			CALLCal)
xx(ADDRG,		5,			ADDRGCal)
xx(ADD,			6,			ADDCal)
xx(SUB,			7,			SUBCal)
xx(DIV,			8,			DIVCal)
xx(MUL,			9,			MULCal)
xx(EQ,			10,			EQCal)
xx(GE,			11,			GECal)
xx(GT,			12,			GTCal)
xx(LE,			13,			LECal)
xx(LT,			14,			LTCal)
xx(NE,			15,			NECal)
yy(JUMP,		30,			0)
yy(LABEL,		31,			0)
yy(NEG,			32,			0)
yy(AND,			33,			0)
yy(NOT,			34,			0)
yy(OR,			35,			0)
yy(COND,		36,			0)
yy(RIGHT,		37,			0)
#undef xx
#undef yy